config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  devise_for :guests
  resources :visitors
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :guest
end

app/models/guest.rb
class Guest < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :visitor
         has_many :feedback
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    belongs_to :guest

    validates :name, :phone_number, :reason_of_visit, :guest_id, presence: true, allow_nil: true
    validates :phone_number, length: { is: 10 }
    validates :reason_of_visit, length: { maximum: 100 }
    validates :reason_of_visit, length: { minimum: 5 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: %i[name phone_number])
        devise_parameter_sanitizer.permit(:account_update, keys: %i[name phone_number])

    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]
  before_action :authenticate_guest!, except: %i[index new create show]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:feedback, :guest_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about; end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[show edit update destroy]
  before_action :authenticate_guest!, except: %i[index new create show]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
    if @visitor.guest != current_guest
      redirect_to @visitor, notice: "Not Authorized"
    end
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    if @visitor.guest == current_guest
      @visitor.destroy
      respond_to do |format|
        format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @visitor, notice: "Not Authorized"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:checked_in, :name, :phone_number, :guest_id, :reason_of_visit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :feedback, class: 'form-label' %>
    <%= form.text_area :feedback, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :guest_id, class: 'form-control', value: 10, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
    <%= link_to 'Feedbacks', feedbacks_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/feedbacks/_mark.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :feedback, class: 'form-label' %>
    <%= form.text_area :feedback, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :guest_id, class: 'form-control', value: current_guest.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<div class="card text-center">
  <div class="card-body">
    <h1>Editing Feedback</h1>
    <br>
    <%= render 'form', feedback: @feedback %>
    
    <%= link_to 'Show', @feedback, class:'btn btn-primary' %>
    <%= link_to 'Back', feedbacks_path, class:'btn btn-secondary' %>
  </div>
</div>
<br>

app/views/feedbacks/index.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header">
    <h1>Feedbacks</h1>
  </div>
  <div class="card-body">
    <table class="table table-success table-striped table-hover ">
      <thead>
        <tr>
          <th>Feedback</th>
          <th colspan="3"></th>
        </tr>
      </thead>
  
      <tbody>
        <% @feedbacks.each do |feedback| %>
          <tr>
            <td><%= feedback.feedback %></td>
            <td><%= link_to 'Show', feedback %></td>
            <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
            <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= link_to 'New Feedback', new_feedback_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/feedbacks/new.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header text-center">
    <h1>New Feedback</h1>
  </div>
  <div class="card-body">
    <% if guest_signed_in? %>
      <%= render 'mark', feedback: @feedback %>
    <% else %>
      <%= render 'form', feedback: @feedback %>
    <% end %>

    <%= link_to 'Back', feedbacks_path, class:'btn btn-secondary' %>
  </div>
</div>
<br>

app/views/feedbacks/show.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header">
    <%= @feedback.created_at %>
  </div>
  <div class="card-body">
    <p class="card-text"> <%= @feedback.feedback %> </p>
  </div>
  <div class="card-footer">
  <%= link_to 'Edit', edit_feedback_path(@feedback), class:'btn btn-primary' %>
  <%= link_to 'Back', feedbacks_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Visitor\'s Log', root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Mark Entry', new_visitor_path, class:'nav-link' %>
        </li>
        <% if guest_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Entries', visitors_path, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_guest_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log In', new_guest_session_path, class:'nav-link' %>
          </li>
        <% end %>
        <% if guest_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_guest_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_guest_session_path, method: :delete, class:'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Feedback', new_feedback_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:'nav-link' %>
        </li>
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>Visitor logs are an integral part of a visitor management system as it makes sure the person entering the premises has valid credentials to access something, whether it is about visiting someone, or database or system control.</p>

<p>In order to have necessary safety nets in place, it is imperative for organizations to have a proper system and registration process that restricts the entry of unauthorized visitors and ensures workplace safety by all means.</p>

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <title>Log Book</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = 'container'>
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end %>
      <br/>
      <%= yield %>
    </div>  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :checked_in, class:"form-label" %>
    <%= form.label :checked_in, class:"form-control", value:Time.zone.now %>
    <%= form.text_field :checked_in, class:"form-control", value:Time.zone.now, type: :hidden %>
  </div>

  <div class="field mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class:"form-control text-center" %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone_number, class:"form-label" %>
    <%= form.text_field :phone_number, class:"form-control text-center" %>
  </div>

  <div class="field mb-3">
    <%= form.label :reason_of_visit, class:"form-label" %>
    <%= form.text_area :reason_of_visit, class:"form-control text-center" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :guest_id, id: :visitor_guest_id, class:"form-control", value: 10, type: :hidden %>
  </div>

  <div class="actions mb-3">
    <%= form.submit 'Mark', class:'btn btn-success' %>
  </div>
<% end %>

app/views/visitors/_mark.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :checked_in, class:"form-label" %>
    <%= form.label :checked_in, class:"form-control", value:Time.zone.now %>
    <%= form.text_field :checked_in, class:"form-control", value:Time.zone.now, type: :hidden %>
  </div>

  <div class="field mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.label :name, class:"form-control text-center", value:current_guest.name %>
    <%= form.text_field :name, class:"form-control text-center", value:current_guest.name, type: :hidden %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone_number, class:"form-label" %>
    <%= form.label :phone_number, class:"form-control text-center", value: current_guest.phone_number %>
    <%= form.text_field :phone_number, class:"form-control text-center", value: current_guest.phone_number, type: :hidden %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :guest_id, id: :visitor_guest_id, class:"form-control", value: current_guest.id, type: :hidden %>
  </div>

  <div class="field mb-3">
    <%= form.label :reason_of_visit, class:"form-label" %>
    <%= form.text_area :reason_of_visit, class:"form-control text-center" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit 'Mark', class:'btn btn-success' %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<div class="card text-center">
  <div class="card-body">
    <h1>Editing Visitor</h1>
    <br>
    <%= render 'form', visitor: @visitor %>
    
    <%= link_to 'Show', @visitor, class:'btn btn-primary' %> 
    <%= link_to 'Back', visitors_path, class:'btn btn-secondary' %>
  </div>
</div>
<br>

app/views/visitors/index.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header">
    <h1>Visitors</h1>
  </div>
  <div class="card-body">
    <table class="table table-success table-striped table-hover ">
      <thead>
        <tr>
          <th>Checked in</th>
          <th>Name</th>
          <th>Phone number</th>
          <th>Reason of visit</th>
          <th colspan="3"></th>
        </tr>
      </thead>
  
      <tbody>
        <% @visitors.each do |visitor| %>
          <tr>
            <td><%= visitor.created_at %></td>
            <td><%= visitor.name %></td>
            <td><%= visitor.phone_number %></td>
            <td><%= visitor.reason_of_visit %></td>
            <td><%= link_to 'Show', visitor %></td>
            <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
            <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= link_to 'Mark Entry', new_visitor_path, class: 'btn btn-success'%>
  </div>
</div>

app/views/visitors/new.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header text-center">
    <h1>Mark Entry</h1>
  </div>
  <div class="card-body">
    <% if guest_signed_in? %>
      <%= render 'mark', visitor: @visitor %>
    <% else %>
      <%= render 'form', visitor: @visitor %>
    <% end %>

    <%= link_to 'Back', visitors_path, class:'btn btn-secondary' %>
  </div>
</div>
<br>

app/views/visitors/show.html.erb
<div class="card text-center shadow-lg mb-5">
  <div class="card-header">
    <%= @visitor.created_at %>
  </div>
  <div class="card-body">
    <h4 class="card-title"> <%= @visitor.name %> </h4>
    <h5 class='card-subtitle mb-2 text-muted'> <%= @visitor.phone_number %> </h5>
    <p class="card-text"> <%= @visitor.reason_of_visit %> </p>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_visitor_path(@visitor), class:'btn btn-primary' %> 
    <%= link_to 'Back', visitors_path, class: 'btn btn-secondary' %>
  </div>
</div>